import Head from "next/head";
import { Box } from "@mui/system";
import { Button, Container, Typography } from "@mui/material";

import Navbar from "../components/Navbar/Navbar.jsx";
import MovieList from "../components/MovieList/MovieList.jsx";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlay, faPlus } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  return (
    <div className="app-container">
      <Head>
        <title>Popflix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container maxWidth="xxl">
        <Navbar />
        <Box
          sx={{
            display: "flex",
            flexDirection: ["column", "column", "row"],
            minHeight: "85vh",
            width: "100%",
          }}
        >
          <Box
            sx={{
              width: ["100%", "100%", "80%"],
              px: 3,
              display: "flex",
              marginTop: ["50px", "50px", 0],
              paddingBottom: ["50px", "100px"],
            }}
          >
            <Box sx={{ alignSelf: "flex-end" }}>
              <Typography variant="h6">POPFLIX ORIGINAL</Typography>
              <Typography variant="h1">THE KINGS ARMY</Typography>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: ["column", "row"],
                  mt: 3,
                }}
              >
                <Button
                  variant="contained"
                  size="large"
                  color="primary"
                  sx={{ px: 5 }}
                  startIcon={<FontAwesomeIcon icon={faPlay} />}
                >
                  WATCH NOW
                </Button>
                <Button
                  variant="outlined"
                  size="large"
                  color="primary"
                  sx={{ px: 5, ml: [0, 2], mt: [2, 0] }}
                  startIcon={<FontAwesomeIcon icon={faPlus} />}
                >
                  MY PLAYLIST
                </Button>
              </Box>
            </Box>
          </Box>
          <Box
            sx={{
              width: ["100%", "100%", "20%"],
              minWidth: "300px",
              minHeight: "65vh",
              display: "flex",
              justifyContent: "center",
            }}
          >
            <MovieList />
          </Box>
        </Box>
      </Container>
    </div>
  );
}
