import { Container } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";

import Navbar from "../components/Navbar/Navbar.jsx";
import MovieCard from "../components/MovieCard/MovieCard.jsx";

export default function Home() {
  return (
    <div className="app-container">
      <Head>
        <title>Popflix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container maxWidth="xxl">
        <Navbar />
        <Box sx={{ display: "flex", height: "80vh", width: "100%" }}>
          <Box sx={{ width: "80%", px: 3 }}>
            <div>hola</div>
          </Box>
          <Box sx={{ width: "20%" }}>
            <MovieCard />
          </Box>
        </Box>
      </Container>
    </div>
  );
}
